import re
from datetime import datetime, timezone
from pathlib import Path

from pypdf import PdfReader


def normalize_text(text: str) -> str:
    normalized = text.replace("\r\n", "\n").replace("\r", "\n")
    normalized = re.sub(r"[ \t]+", " ", normalized)
    normalized = re.sub(r"\n{3,}", "\n\n", normalized)
    return normalized.strip()


def extract_text_from_pdf(file_path: Path) -> str:
    reader = PdfReader(str(file_path))
    pages: list[str] = []

    for index, page in enumerate(reader.pages, start=1):
        page_text = normalize_text(page.extract_text() or "")
        if page_text:
            pages.append(f"[Page {index}]\n{page_text}")

    return "\n\n".join(pages).strip()


def build_formalization_bundle(
    *,
    title: str,
    source_text: str,
    source_kind: str,
    source_filename: str | None = None,
) -> dict[str, str]:
    working_text = normalize_text(source_text)
    if not working_text:
        raise ValueError("Proof text is empty.")

    theorem_identifier = _to_identifier(title)
    excerpt = _excerpt(working_text)
    steps: list[dict[str, str]] = []

    if source_kind == "pdf":
        steps.append(
            _build_step(
                agent_id="pdf-ingestor",
                agent_name="PDF Ingestor",
                stage="pdf_to_text",
                summary=(
                    f"Extracted {len(working_text)} characters from "
                    f"{source_filename or 'uploaded PDF'}."
                ),
                output_preview=excerpt,
            )
        )
    else:
        steps.append(
            _build_step(
                agent_id="proof-editor",
                agent_name="Proof Editor",
                stage="editor_to_text",
                summary="Normalized the uploaded proof draft into a conversion-ready text representation.",
                output_preview=excerpt,
            )
        )

    lean4_code = _generate_lean4_code(title, theorem_identifier, excerpt)
    steps.append(
        _build_step(
            agent_id="lean4-formalizer",
            agent_name="Lean4 Formalizer",
            stage="text_to_lean4",
            summary="Generated a Lean4 starter theorem with a placeholder proposition and preserved source context in comments.",
            output_preview=lean4_code,
        )
    )

    rocq_code = _generate_rocq_code(title, theorem_identifier, excerpt)
    steps.append(
        _build_step(
            agent_id="rocq-formalizer",
            agent_name="Rocq Formalizer",
            stage="text_to_rocq",
            summary="Generated a Rocq starter theorem directly from the normalized proof text so the Rocq track can evolve independently.",
            output_preview=rocq_code,
        )
    )

    return {
        "source_text": working_text,
        "extracted_text": working_text,
        "lean4_code": lean4_code,
        "rocq_code": rocq_code,
        "status": "generated",
        "agent_trace_json": _json_dumps(steps),
    }


def _build_step(
    *,
    agent_id: str,
    agent_name: str,
    stage: str,
    summary: str,
    output_preview: str,
) -> dict[str, str]:
    return {
        "agent_id": agent_id,
        "agent_name": agent_name,
        "stage": stage,
        "summary": summary,
        "output_preview": _excerpt(output_preview, limit=360),
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }


def _to_identifier(title: str) -> str:
    identifier = re.sub(r"[^a-zA-Z0-9]+", "_", title.lower()).strip("_")
    if not identifier:
        identifier = "uploaded_proof"
    if identifier[0].isdigit():
        identifier = f"proof_{identifier}"
    return identifier


def _excerpt(text: str, *, limit: int = 700) -> str:
    clipped = text.strip()
    if len(clipped) <= limit:
        return clipped
    return f"{clipped[:limit].rstrip()}..."


def _generate_lean4_code(title: str, theorem_identifier: str, excerpt: str) -> str:
    return (
        "/-\n"
        "Auto-generated by Shannon Manifold.\n"
        f"Source title: {title}\n\n"
        "Source excerpt:\n"
        f"{excerpt}\n\n"
        "TODO:\n"
        "- Replace `True` with the exact proposition.\n"
        "- Formalize hypotheses and imported dependencies.\n"
        "- Replace the trivial proof with the actual Lean4 proof.\n"
        "-/\n\n"
        "import ShannonManifold\n\n"
        "open ShannonManifold\n\n"
        f"theorem {theorem_identifier}_draft : True := by\n"
        "  trivial\n"
    )


def _generate_rocq_code(title: str, theorem_identifier: str, excerpt: str) -> str:
    return (
        "(*\n"
        "Auto-generated by Shannon Manifold.\n"
        f"Source title: {title}\n\n"
        "Source excerpt:\n"
        f"{excerpt}\n\n"
        "TODO:\n"
        "- Replace `True` with the exact proposition.\n"
        "- Add the necessary imports and local hypotheses.\n"
        "- Replace the trivial proof with the actual Rocq proof.\n"
        "*)\n\n"
        f"Theorem {theorem_identifier}_draft : True.\n"
        "Proof.\n"
        "  exact I.\n"
        "Qed.\n"
    )


def _json_dumps(steps: list[dict[str, str]]) -> str:
    import json

    return json.dumps(steps)
